<?php

namespace Database\Seeders;

use App\Models\Jorong;
use Illuminate\Database\Seeder;

class JorongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data lama
        Jorong::query()->delete();
        
        $jorongs = [
            ['id' => 1, 'nagari_id' => 1, 'nama_jorong' => 'Pantai Cermin', 'jumlah_penduduk_jorong' => 1245],
            ['id' => 2, 'nagari_id' => 1, 'nama_jorong' => 'Tambang Ameh', 'jumlah_penduduk_jorong' => 987],
            ['id' => 3, 'nagari_id' => 1, 'nama_jorong' => 'Tanjung Udani', 'jumlah_penduduk_jorong' => 1156],
            ['id' => 4, 'nagari_id' => 1, 'nama_jorong' => 'Ranah Tibarau', 'jumlah_penduduk_jorong' => 834],
            ['id' => 5, 'nagari_id' => 1, 'nama_jorong' => 'Lintas Harapan', 'jumlah_penduduk_jorong' => 1098],
            ['id' => 6, 'nagari_id' => 2, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 1567],
            ['id' => 7, 'nagari_id' => 2, 'nama_jorong' => 'Simpang Ampek', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 8, 'nagari_id' => 2, 'nama_jorong' => 'Koto Panjang', 'jumlah_penduduk_jorong' => 1089],
            ['id' => 9, 'nagari_id' => 3, 'nama_jorong' => 'Tanjung Pauh', 'jumlah_penduduk_jorong' => 945],
            ['id' => 10, 'nagari_id' => 3, 'nama_jorong' => 'Dusun Tuo', 'jumlah_penduduk_jorong' => 1123],
            ['id' => 11, 'nagari_id' => 3, 'nama_jorong' => 'Bungo Pinang', 'jumlah_penduduk_jorong' => 876],
            ['id' => 12, 'nagari_id' => 4, 'nama_jorong' => 'Ranah Pasar', 'jumlah_penduduk_jorong' => 1345],
            ['id' => 13, 'nagari_id' => 4, 'nama_jorong' => 'Kampung Pinang', 'jumlah_penduduk_jorong' => 1098],
            ['id' => 14, 'nagari_id' => 4, 'nama_jorong' => 'Tanjung Raya', 'jumlah_penduduk_jorong' => 987],
            ['id' => 15, 'nagari_id' => 5, 'nama_jorong' => 'Bukik Malintang', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 16, 'nagari_id' => 5, 'nama_jorong' => 'Rantau Jambu', 'jumlah_penduduk_jorong' => 1156],
            ['id' => 17, 'nagari_id' => 5, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 876],
            ['id' => 18, 'nagari_id' => 6, 'nama_jorong' => 'Cilacap', 'jumlah_penduduk_jorong' => 1567],
            ['id' => 19, 'nagari_id' => 6, 'nama_jorong' => 'Talang', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 20, 'nagari_id' => 6, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 1089],
            ['id' => 21, 'nagari_id' => 6, 'nama_jorong' => 'Sikayan', 'jumlah_penduduk_jorong' => 945],
            ['id' => 22, 'nagari_id' => 6, 'nama_jorong' => 'Sungai Ampang', 'jumlah_penduduk_jorong' => 1123],
            ['id' => 23, 'nagari_id' => 6, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 876],
            ['id' => 24, 'nagari_id' => 6, 'nama_jorong' => 'Batang Tonam', 'jumlah_penduduk_jorong' => 1345],
            ['id' => 25, 'nagari_id' => 7, 'nama_jorong' => 'Batang Kariang', 'jumlah_penduduk_jorong' => 1098],
            ['id' => 26, 'nagari_id' => 7, 'nama_jorong' => 'Galogah', 'jumlah_penduduk_jorong' => 987],
            ['id' => 27, 'nagari_id' => 7, 'nama_jorong' => 'Kamang', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 28, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Abadi', 'jumlah_penduduk_jorong' => 1156],
            ['id' => 29, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Bhakti', 'jumlah_penduduk_jorong' => 876],
            ['id' => 30, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Makmur', 'jumlah_penduduk_jorong' => 1567],
            ['id' => 31, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Sejahtera', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 32, 'nagari_id' => 7, 'nama_jorong' => 'Kurnia Kamang', 'jumlah_penduduk_jorong' => 1089],
            ['id' => 33, 'nagari_id' => 7, 'nama_jorong' => 'Simpang Kamang', 'jumlah_penduduk_jorong' => 945],
            ['id' => 34, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Sentosa', 'jumlah_penduduk_jorong' => 1123],
            ['id' => 35, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Madani', 'jumlah_penduduk_jorong' => 876],
            ['id' => 36, 'nagari_id' => 8, 'nama_jorong' => 'Dusun Tinggi I', 'jumlah_penduduk_jorong' => 1345],
            ['id' => 37, 'nagari_id' => 8, 'nama_jorong' => 'Kiliran Jao', 'jumlah_penduduk_jorong' => 1098],
            ['id' => 38, 'nagari_id' => 8, 'nama_jorong' => 'Batu Talang', 'jumlah_penduduk_jorong' => 987],
            ['id' => 39, 'nagari_id' => 8, 'nama_jorong' => 'Koto Lamo', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 40, 'nagari_id' => 8, 'nama_jorong' => 'Batang Tiau', 'jumlah_penduduk_jorong' => 1156],
            ['id' => 41, 'nagari_id' => 8, 'nama_jorong' => 'Koto Rona', 'jumlah_penduduk_jorong' => 876],
            ['id' => 42, 'nagari_id' => 8, 'nama_jorong' => 'Sungai Sariek', 'jumlah_penduduk_jorong' => 1567],
            ['id' => 43, 'nagari_id' => 9, 'nama_jorong' => 'Guguk Tinggi', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 44, 'nagari_id' => 9, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 1089],
            ['id' => 45, 'nagari_id' => 9, 'nama_jorong' => 'Banjar Tengah', 'jumlah_penduduk_jorong' => 945],
            ['id' => 46, 'nagari_id' => 9, 'nama_jorong' => 'Lubuk Kapiek', 'jumlah_penduduk_jorong' => 1123],
            ['id' => 47, 'nagari_id' => 9, 'nama_jorong' => 'Koto Ronah', 'jumlah_penduduk_jorong' => 876],
            ['id' => 48, 'nagari_id' => 9, 'nama_jorong' => 'Koto Tuo', 'jumlah_penduduk_jorong' => 1345],
            ['id' => 49, 'nagari_id' => 10, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 1098],
            ['id' => 50, 'nagari_id' => 10, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 987],
            ['id' => 51, 'nagari_id' => 10, 'nama_jorong' => 'Banjar Pematang', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 52, 'nagari_id' => 11, 'nama_jorong' => 'Kunangan', 'jumlah_penduduk_jorong' => 1156],
            ['id' => 53, 'nagari_id' => 11, 'nama_jorong' => 'Parik Rantang', 'jumlah_penduduk_jorong' => 876],
            ['id' => 54, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang I', 'jumlah_penduduk_jorong' => 1567],
            ['id' => 55, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang II', 'jumlah_penduduk_jorong' => 1234],
            ['id' => 56, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang III', 'jumlah_penduduk_jorong' => 1089],
            ['id' => 57, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang IV', 'jumlah_penduduk_jorong' => 945],
            ['id' => 58, 'nagari_id' => 11, 'nama_jorong' => 'Mekar Jaya Sungai Tenang', 'jumlah_penduduk_jorong' => 1123],
            ['id' => 59, 'nagari_id' => 11, 'nama_jorong' => 'Suka Maju Sungai Tenang', 'jumlah_penduduk_jorong' => 876],
            ['id' => 60, 'nagari_id' => 11, 'nama_jorong' => 'Suko Rejo Sungai Tenang', 'jumlah_penduduk_jorong' => 1345],
            // Data dari SQL file success5_infrastruktur.sql
            ['id' => 809, 'nagari_id' => 42, 'nama_jorong' => 'Padang Ranah', 'jumlah_penduduk_jorong' => 679],
            ['id' => 810, 'nagari_id' => 42, 'nama_jorong' => 'Tapian Nanto', 'jumlah_penduduk_jorong' => 896],
            ['id' => 811, 'nagari_id' => 42, 'nama_jorong' => 'Kandang Harimau', 'jumlah_penduduk_jorong' => 744],
            ['id' => 812, 'nagari_id' => 42, 'nama_jorong' => 'Tapian Diaro', 'jumlah_penduduk_jorong' => 530],
            ['id' => 813, 'nagari_id' => 42, 'nama_jorong' => 'Kampung Berlian', 'jumlah_penduduk_jorong' => 934],
            ['id' => 814, 'nagari_id' => 42, 'nama_jorong' => 'Pudak', 'jumlah_penduduk_jorong' => 794],
            ['id' => 815, 'nagari_id' => 42, 'nama_jorong' => 'Kampung Baru', 'jumlah_penduduk_jorong' => 976],
            ['id' => 816, 'nagari_id' => 42, 'nama_jorong' => 'Pasar Sijunjung', 'jumlah_penduduk_jorong' => 922],
            ['id' => 817, 'nagari_id' => 42, 'nama_jorong' => 'Tanah Bato', 'jumlah_penduduk_jorong' => 1232],
            ['id' => 818, 'nagari_id' => 42, 'nama_jorong' => 'Ganting', 'jumlah_penduduk_jorong' => 2485],
            ['id' => 819, 'nagari_id' => 44, 'nama_jorong' => 'Simawik', 'jumlah_penduduk_jorong' => 552],
            ['id' => 820, 'nagari_id' => 44, 'nama_jorong' => 'Rumbai', 'jumlah_penduduk_jorong' => 466],
            ['id' => 821, 'nagari_id' => 44, 'nama_jorong' => 'Sungai Tampang', 'jumlah_penduduk_jorong' => 662],
            ['id' => 822, 'nagari_id' => 44, 'nama_jorong' => 'Sibolin', 'jumlah_penduduk_jorong' => 242],
            ['id' => 823, 'nagari_id' => 44, 'nama_jorong' => 'Koto Sisawah', 'jumlah_penduduk_jorong' => 485],
            ['id' => 824, 'nagari_id' => 44, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 536],
            ['id' => 825, 'nagari_id' => 44, 'nama_jorong' => 'Kabun', 'jumlah_penduduk_jorong' => 589],
            ['id' => 826, 'nagari_id' => 45, 'nama_jorong' => 'Koto Unggan', 'jumlah_penduduk_jorong' => 948],
            ['id' => 827, 'nagari_id' => 45, 'nama_jorong' => 'Unggan Bukik', 'jumlah_penduduk_jorong' => 783],
            ['id' => 828, 'nagari_id' => 45, 'nama_jorong' => 'Taratak Aro', 'jumlah_penduduk_jorong' => 604],
            ['id' => 829, 'nagari_id' => 45, 'nama_jorong' => 'Lubuak Batapuak Unggan', 'jumlah_penduduk_jorong' => 681],
            ['id' => 830, 'nagari_id' => 45, 'nama_jorong' => 'Kinkin', 'jumlah_penduduk_jorong' => 350],
            ['id' => 831, 'nagari_id' => 45, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 413],
            ['id' => 832, 'nagari_id' => 45, 'nama_jorong' => 'Koto Ateh', 'jumlah_penduduk_jorong' => 398],
            ['id' => 833, 'nagari_id' => 45, 'nama_jorong' => 'Ujung Koto', 'jumlah_penduduk_jorong' => 504],
            ['id' => 834, 'nagari_id' => 45, 'nama_jorong' => 'Batang Kinkin', 'jumlah_penduduk_jorong' => 426],
            ['id' => 835, 'nagari_id' => 46, 'nama_jorong' => 'Bonai', 'jumlah_penduduk_jorong' => 470],
            ['id' => 836, 'nagari_id' => 46, 'nama_jorong' => 'Koto Tinggi', 'jumlah_penduduk_jorong' => 465],
            ['id' => 837, 'nagari_id' => 46, 'nama_jorong' => 'Pauh', 'jumlah_penduduk_jorong' => 383],
            ['id' => 838, 'nagari_id' => 46, 'nama_jorong' => 'Loban Bungkuok', 'jumlah_penduduk_jorong' => 431],
            ['id' => 839, 'nagari_id' => 46, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 674],
            ['id' => 840, 'nagari_id' => 46, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 501],
            ['id' => 841, 'nagari_id' => 47, 'nama_jorong' => 'Pintu Rayo', 'jumlah_penduduk_jorong' => 388],
            ['id' => 842, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Ujung Luhak', 'jumlah_penduduk_jorong' => 420],
            ['id' => 843, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Tangah', 'jumlah_penduduk_jorong' => 328],
            ['id' => 844, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Sipuah', 'jumlah_penduduk_jorong' => 257],
            ['id' => 845, 'nagari_id' => 47, 'nama_jorong' => 'Tombang', 'jumlah_penduduk_jorong' => 470],
            ['id' => 846, 'nagari_id' => 47, 'nama_jorong' => 'Kampung Rajo', 'jumlah_penduduk_jorong' => 320],
            ['id' => 847, 'nagari_id' => 47, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 393],
            ['id' => 848, 'nagari_id' => 47, 'nama_jorong' => 'Batang Somi', 'jumlah_penduduk_jorong' => 440],
            ['id' => 849, 'nagari_id' => 47, 'nama_jorong' => 'Payo Sahadat', 'jumlah_penduduk_jorong' => 327],
            ['id' => 850, 'nagari_id' => 48, 'nama_jorong' => 'Sitongek', 'jumlah_penduduk_jorong' => 399],
            ['id' => 851, 'nagari_id' => 48, 'nama_jorong' => 'Koto Lamo', 'jumlah_penduduk_jorong' => 348],
            ['id' => 852, 'nagari_id' => 48, 'nama_jorong' => 'Pangkahan Sungai Laban', 'jumlah_penduduk_jorong' => 132],
            ['id' => 853, 'nagari_id' => 48, 'nama_jorong' => 'Simaru', 'jumlah_penduduk_jorong' => 520],
            ['id' => 854, 'nagari_id' => 48, 'nama_jorong' => 'Sitongek Selatan', 'jumlah_penduduk_jorong' => 277],
            ['id' => 855, 'nagari_id' => 48, 'nama_jorong' => 'Koto Lamo Utara', 'jumlah_penduduk_jorong' => 355],
            ['id' => 856, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Alam', 'jumlah_penduduk_jorong' => 801],
            ['id' => 857, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Raya', 'jumlah_penduduk_jorong' => 338],
            ['id' => 858, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Gadang', 'jumlah_penduduk_jorong' => 354],
            ['id' => 859, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Gadang Utara', 'jumlah_penduduk_jorong' => 362],
            ['id' => 860, 'nagari_id' => 50, 'nama_jorong' => 'Tapi Balai', 'jumlah_penduduk_jorong' => 466],
            ['id' => 861, 'nagari_id' => 50, 'nama_jorong' => 'Balai Lamo', 'jumlah_penduduk_jorong' => 578],
            ['id' => 862, 'nagari_id' => 50, 'nama_jorong' => 'Taruko', 'jumlah_penduduk_jorong' => 488],
            ['id' => 863, 'nagari_id' => 52, 'nama_jorong' => 'Simpang Tigo Sabiluru', 'jumlah_penduduk_jorong' => 560],
            ['id' => 864, 'nagari_id' => 52, 'nama_jorong' => 'Sipuah', 'jumlah_penduduk_jorong' => 419],
            ['id' => 865, 'nagari_id' => 52, 'nama_jorong' => 'Simpang Sawah Silupak', 'jumlah_penduduk_jorong' => 261],
            ['id' => 866, 'nagari_id' => 53, 'nama_jorong' => 'Pincuran Tujuh', 'jumlah_penduduk_jorong' => 666],
            ['id' => 867, 'nagari_id' => 53, 'nama_jorong' => 'Air Seriau', 'jumlah_penduduk_jorong' => 519],
            ['id' => 868, 'nagari_id' => 53, 'nama_jorong' => 'Payo Lawe', 'jumlah_penduduk_jorong' => 415],
            ['id' => 869, 'nagari_id' => 53, 'nama_jorong' => 'Kuok', 'jumlah_penduduk_jorong' => 396],
            ['id' => 870, 'nagari_id' => 53, 'nama_jorong' => 'Koto Puntian', 'jumlah_penduduk_jorong' => 300],
            ['id' => 871, 'nagari_id' => 53, 'nama_jorong' => 'Uncang Labuah', 'jumlah_penduduk_jorong' => 426],
            ['id' => 872, 'nagari_id' => 53, 'nama_jorong' => 'Calau', 'jumlah_penduduk_jorong' => 766],
            ['id' => 873, 'nagari_id' => 53, 'nama_jorong' => 'Kampung Baru', 'jumlah_penduduk_jorong' => 519],
            ['id' => 874, 'nagari_id' => 54, 'nama_jorong' => 'Balai-Balai', 'jumlah_penduduk_jorong' => 748],
            ['id' => 875, 'nagari_id' => 54, 'nama_jorong' => 'Koto Timbulun', 'jumlah_penduduk_jorong' => 867],
            ['id' => 876, 'nagari_id' => 54, 'nama_jorong' => 'Sibisir', 'jumlah_penduduk_jorong' => 957],
            ['id' => 877, 'nagari_id' => 54, 'nama_jorong' => 'Tandikek', 'jumlah_penduduk_jorong' => 629],
            ['id' => 878, 'nagari_id' => 55, 'nama_jorong' => 'Pasar Tanjung Gadang', 'jumlah_penduduk_jorong' => 456],
            ['id' => 879, 'nagari_id' => 55, 'nama_jorong' => 'Mudik Malih', 'jumlah_penduduk_jorong' => 137],
            ['id' => 880, 'nagari_id' => 55, 'nama_jorong' => 'Guguk Naneh', 'jumlah_penduduk_jorong' => 371],
            ['id' => 881, 'nagari_id' => 55, 'nama_jorong' => 'Pandam', 'jumlah_penduduk_jorong' => 193],
            ['id' => 882, 'nagari_id' => 55, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 256],
            ['id' => 883, 'nagari_id' => 55, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => 306],
            ['id' => 884, 'nagari_id' => 55, 'nama_jorong' => 'Sungai Napar', 'jumlah_penduduk_jorong' => 136],
            ['id' => 885, 'nagari_id' => 55, 'nama_jorong' => 'Timbulun Patah', 'jumlah_penduduk_jorong' => 185],
            ['id' => 886, 'nagari_id' => 55, 'nama_jorong' => 'Kayu Gadih', 'jumlah_penduduk_jorong' => 227],
            ['id' => 887, 'nagari_id' => 56, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 166],
            ['id' => 888, 'nagari_id' => 56, 'nama_jorong' => 'Ranah Palam', 'jumlah_penduduk_jorong' => 144],
            ['id' => 889, 'nagari_id' => 56, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => 109],
            ['id' => 890, 'nagari_id' => 57, 'nama_jorong' => 'Padang Laweh', 'jumlah_penduduk_jorong' => 538],
            ['id' => 891, 'nagari_id' => 57, 'nama_jorong' => 'Sungai Kandi', 'jumlah_penduduk_jorong' => 143],
            ['id' => 892, 'nagari_id' => 57, 'nama_jorong' => 'Koto Pulasan', 'jumlah_penduduk_jorong' => 720],
            ['id' => 893, 'nagari_id' => 57, 'nama_jorong' => 'Sawah Gadang', 'jumlah_penduduk_jorong' => 178],
            ['id' => 894, 'nagari_id' => 57, 'nama_jorong' => 'Ambacang', 'jumlah_penduduk_jorong' => 756],
            ['id' => 895, 'nagari_id' => 57, 'nama_jorong' => 'Pasar Pulasan', 'jumlah_penduduk_jorong' => 823],
            ['id' => 896, 'nagari_id' => 57, 'nama_jorong' => 'Batang Kati', 'jumlah_penduduk_jorong' => 484],
            ['id' => 897, 'nagari_id' => 58, 'nama_jorong' => 'Koto Langki', 'jumlah_penduduk_jorong' => 141],
            ['id' => 898, 'nagari_id' => 58, 'nama_jorong' => 'Liambang', 'jumlah_penduduk_jorong' => 271],
            ['id' => 899, 'nagari_id' => 58, 'nama_jorong' => 'Muaro Kaluai', 'jumlah_penduduk_jorong' => 82],
            ['id' => 900, 'nagari_id' => 58, 'nama_jorong' => 'Muaro Linggo', 'jumlah_penduduk_jorong' => 192],
            ['id' => 901, 'nagari_id' => 59, 'nama_jorong' => 'Bancah', 'jumlah_penduduk_jorong' => 173],
            ['id' => 902, 'nagari_id' => 59, 'nama_jorong' => 'Lubuk Tolang', 'jumlah_penduduk_jorong' => 87],
            ['id' => 903, 'nagari_id' => 59, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 270],
            ['id' => 904, 'nagari_id' => 60, 'nama_jorong' => 'Pasar Lamo', 'jumlah_penduduk_jorong' => 212],
            ['id' => 905, 'nagari_id' => 60, 'nama_jorong' => 'Bukik Sabalah', 'jumlah_penduduk_jorong' => 291],
            ['id' => 906, 'nagari_id' => 60, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 174],
            ['id' => 907, 'nagari_id' => 60, 'nama_jorong' => 'Batang Dikek', 'jumlah_penduduk_jorong' => 266],
            ['id' => 908, 'nagari_id' => 60, 'nama_jorong' => 'Pasar Baru', 'jumlah_penduduk_jorong' => 207],
            ['id' => 909, 'nagari_id' => 60, 'nama_jorong' => 'Tanjung Medan', 'jumlah_penduduk_jorong' => 219],
            ['id' => 910, 'nagari_id' => 61, 'nama_jorong' => 'Lubuk Cupak', 'jumlah_penduduk_jorong' => 232],
            ['id' => 911, 'nagari_id' => 61, 'nama_jorong' => 'Pisang Kolek', 'jumlah_penduduk_jorong' => 201],
            ['id' => 912, 'nagari_id' => 62, 'nama_jorong' => 'Koto Sinyamu', 'jumlah_penduduk_jorong' => 108],
            ['id' => 913, 'nagari_id' => 62, 'nama_jorong' => 'Polak Sinyamu', 'jumlah_penduduk_jorong' => 89],
            ['id' => 914, 'nagari_id' => 62, 'nama_jorong' => 'Kumbayak', 'jumlah_penduduk_jorong' => 95],
        ];

        foreach ($jorongs as $jorong) {
            Jorong::create($jorong);
        }
    }
}
