<?php

namespace Database\Seeders;

use App\Models\Jorong;
use Illuminate\Database\Seeder;

class JorongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Hapus data lama
        Jorong::query()->delete();
        
        $jorongs = [
            // Data lengkap dari SQL file success5_infrastruktur.sql (ID 609-914)
            ['id' => 609, 'nagari_id' => 1, 'nama_jorong' => 'Pantai Cermin', 'jumlah_penduduk_jorong' => 767],
            ['id' => 610, 'nagari_id' => 1, 'nama_jorong' => 'Tambang Ameh', 'jumlah_penduduk_jorong' => 672],
            ['id' => 611, 'nagari_id' => 1, 'nama_jorong' => 'Tanjung Udani', 'jumlah_penduduk_jorong' => 909],
            ['id' => 612, 'nagari_id' => 1, 'nama_jorong' => 'Ranah Tibarau', 'jumlah_penduduk_jorong' => 740],
            ['id' => 613, 'nagari_id' => 1, 'nama_jorong' => 'Lintas Harapan', 'jumlah_penduduk_jorong' => 886],
            ['id' => 614, 'nagari_id' => 2, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 1212],
            ['id' => 615, 'nagari_id' => 2, 'nama_jorong' => 'Simpang Ampek', 'jumlah_penduduk_jorong' => 810],
            ['id' => 616, 'nagari_id' => 2, 'nama_jorong' => 'Koto Panjang', 'jumlah_penduduk_jorong' => 1213],
            ['id' => 617, 'nagari_id' => 3, 'nama_jorong' => 'Tanjung Pauh', 'jumlah_penduduk_jorong' => 1180],
            ['id' => 618, 'nagari_id' => 3, 'nama_jorong' => 'Dusun Tuo', 'jumlah_penduduk_jorong' => 1609],
            ['id' => 619, 'nagari_id' => 3, 'nama_jorong' => 'Bungo Pinang', 'jumlah_penduduk_jorong' => 775],
            ['id' => 620, 'nagari_id' => 4, 'nama_jorong' => 'Ranah Pasar', 'jumlah_penduduk_jorong' => 1153],
            ['id' => 621, 'nagari_id' => 4, 'nama_jorong' => 'Kampung Pinang', 'jumlah_penduduk_jorong' => 952],
            ['id' => 622, 'nagari_id' => 4, 'nama_jorong' => 'Tanjung Raya', 'jumlah_penduduk_jorong' => 962],
            ['id' => 623, 'nagari_id' => 5, 'nama_jorong' => 'Bukik Malintang', 'jumlah_penduduk_jorong' => 650],
            ['id' => 624, 'nagari_id' => 5, 'nama_jorong' => 'Rantau Jambu', 'jumlah_penduduk_jorong' => 631],
            ['id' => 625, 'nagari_id' => 5, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 491],
            ['id' => 626, 'nagari_id' => 6, 'nama_jorong' => 'Cilacap', 'jumlah_penduduk_jorong' => 889],
            ['id' => 627, 'nagari_id' => 6, 'nama_jorong' => 'Talang', 'jumlah_penduduk_jorong' => 1058],
            ['id' => 628, 'nagari_id' => 6, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 936],
            ['id' => 629, 'nagari_id' => 6, 'nama_jorong' => 'Sikayan', 'jumlah_penduduk_jorong' => 882],
            ['id' => 630, 'nagari_id' => 6, 'nama_jorong' => 'Sungai Ampang', 'jumlah_penduduk_jorong' => 878],
            ['id' => 631, 'nagari_id' => 6, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 514],
            ['id' => 632, 'nagari_id' => 6, 'nama_jorong' => 'Batang Tonam', 'jumlah_penduduk_jorong' => 480],
            ['id' => 633, 'nagari_id' => 7, 'nama_jorong' => 'Batang Kariang', 'jumlah_penduduk_jorong' => 446],
            ['id' => 634, 'nagari_id' => 7, 'nama_jorong' => 'Galogah', 'jumlah_penduduk_jorong' => 815],
            ['id' => 635, 'nagari_id' => 7, 'nama_jorong' => 'Kamang', 'jumlah_penduduk_jorong' => 1020],
            ['id' => 636, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Abadi', 'jumlah_penduduk_jorong' => 900],
            ['id' => 637, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Bhakti', 'jumlah_penduduk_jorong' => 934],
            ['id' => 638, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Makmur', 'jumlah_penduduk_jorong' => 1642],
            ['id' => 639, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Sejahtera', 'jumlah_penduduk_jorong' => 767],
            ['id' => 640, 'nagari_id' => 7, 'nama_jorong' => 'Kurnia Kamang', 'jumlah_penduduk_jorong' => 1590],
            ['id' => 641, 'nagari_id' => 7, 'nama_jorong' => 'Simpang Kamang', 'jumlah_penduduk_jorong' => 1367],
            ['id' => 642, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Sentosa', 'jumlah_penduduk_jorong' => 1099],
            ['id' => 643, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Madani', 'jumlah_penduduk_jorong' => 694],
            ['id' => 644, 'nagari_id' => 8, 'nama_jorong' => 'Dusun Tinggi I', 'jumlah_penduduk_jorong' => null],
            ['id' => 645, 'nagari_id' => 8, 'nama_jorong' => 'Kiliran Jao', 'jumlah_penduduk_jorong' => null],
            ['id' => 646, 'nagari_id' => 8, 'nama_jorong' => 'Batu Talang', 'jumlah_penduduk_jorong' => null],
            ['id' => 647, 'nagari_id' => 8, 'nama_jorong' => 'Koto Lamo', 'jumlah_penduduk_jorong' => null],
            ['id' => 648, 'nagari_id' => 8, 'nama_jorong' => 'Batang Tiau', 'jumlah_penduduk_jorong' => null],
            ['id' => 649, 'nagari_id' => 8, 'nama_jorong' => 'Koto Rona', 'jumlah_penduduk_jorong' => null],
            ['id' => 650, 'nagari_id' => 8, 'nama_jorong' => 'Sungai Sariek', 'jumlah_penduduk_jorong' => null],
            ['id' => 651, 'nagari_id' => 9, 'nama_jorong' => 'Guguk Tinggi', 'jumlah_penduduk_jorong' => null],
            ['id' => 652, 'nagari_id' => 9, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => null],
            ['id' => 653, 'nagari_id' => 9, 'nama_jorong' => 'Banjar Tengah', 'jumlah_penduduk_jorong' => null],
            ['id' => 654, 'nagari_id' => 9, 'nama_jorong' => 'Lubuk Kapiek', 'jumlah_penduduk_jorong' => null],
            ['id' => 655, 'nagari_id' => 9, 'nama_jorong' => 'Koto Ronah', 'jumlah_penduduk_jorong' => null],
            ['id' => 656, 'nagari_id' => 9, 'nama_jorong' => 'Koto Tuo', 'jumlah_penduduk_jorong' => null],
            ['id' => 657, 'nagari_id' => 10, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 1108],
            ['id' => 658, 'nagari_id' => 10, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 611],
            ['id' => 659, 'nagari_id' => 10, 'nama_jorong' => 'Banjar Pematang', 'jumlah_penduduk_jorong' => 775],
            ['id' => 660, 'nagari_id' => 11, 'nama_jorong' => 'Kunangan', 'jumlah_penduduk_jorong' => 1200],
            ['id' => 661, 'nagari_id' => 11, 'nama_jorong' => 'Parik Rantang', 'jumlah_penduduk_jorong' => 1684],
            ['id' => 662, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang I', 'jumlah_penduduk_jorong' => 2759],
            ['id' => 663, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang II', 'jumlah_penduduk_jorong' => 1299],
            ['id' => 664, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang III', 'jumlah_penduduk_jorong' => 1282],
            ['id' => 665, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang IV', 'jumlah_penduduk_jorong' => 926],
            ['id' => 666, 'nagari_id' => 11, 'nama_jorong' => 'Mekar Jaya Sungai Tenang', 'jumlah_penduduk_jorong' => 791],
            ['id' => 667, 'nagari_id' => 11, 'nama_jorong' => 'Suka Maju Sungai Tenang', 'jumlah_penduduk_jorong' => 554],
            ['id' => 668, 'nagari_id' => 11, 'nama_jorong' => 'Suko Rejo Sungai Tenang', 'jumlah_penduduk_jorong' => 817],
            ['id' => 669, 'nagari_id' => 12, 'nama_jorong' => 'Mudiak Imuak', 'jumlah_penduduk_jorong' => 716],
            ['id' => 670, 'nagari_id' => 12, 'nama_jorong' => 'Parik Malintang', 'jumlah_penduduk_jorong' => 741],
            ['id' => 671, 'nagari_id' => 12, 'nama_jorong' => 'Pincuran Tujuah', 'jumlah_penduduk_jorong' => 624],
            ['id' => 672, 'nagari_id' => 13, 'nama_jorong' => 'Binuang Aie Putiah', 'jumlah_penduduk_jorong' => 814],
            ['id' => 673, 'nagari_id' => 13, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 600],
            ['id' => 674, 'nagari_id' => 13, 'nama_jorong' => 'Muaro Buan', 'jumlah_penduduk_jorong' => 426],
            ['id' => 675, 'nagari_id' => 13, 'nama_jorong' => 'Pintu Batu', 'jumlah_penduduk_jorong' => 390],
            ['id' => 676, 'nagari_id' => 14, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 539],
            ['id' => 677, 'nagari_id' => 14, 'nama_jorong' => 'Lambah Gunung', 'jumlah_penduduk_jorong' => 574],
            ['id' => 678, 'nagari_id' => 14, 'nama_jorong' => 'Ranah Pinago', 'jumlah_penduduk_jorong' => 561],
            ['id' => 679, 'nagari_id' => 15, 'nama_jorong' => 'Dusun Tinggi II', 'jumlah_penduduk_jorong' => 800],
            ['id' => 680, 'nagari_id' => 15, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 350],
            ['id' => 681, 'nagari_id' => 15, 'nama_jorong' => 'Lubuk Tarantang', 'jumlah_penduduk_jorong' => 450],
            ['id' => 682, 'nagari_id' => 16, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => 407],
            ['id' => 683, 'nagari_id' => 16, 'nama_jorong' => 'Pasar', 'jumlah_penduduk_jorong' => 527],
            ['id' => 684, 'nagari_id' => 16, 'nama_jorong' => 'Sungai Alai', 'jumlah_penduduk_jorong' => 308],
            ['id' => 685, 'nagari_id' => 16, 'nama_jorong' => 'Sungai Gamuruah', 'jumlah_penduduk_jorong' => 505],
            ['id' => 686, 'nagari_id' => 16, 'nama_jorong' => 'Tanjung Balik', 'jumlah_penduduk_jorong' => 513],
            ['id' => 687, 'nagari_id' => 17, 'nama_jorong' => 'Aur Gading', 'jumlah_penduduk_jorong' => 1218],
            ['id' => 688, 'nagari_id' => 17, 'nama_jorong' => 'Tanjung Ampalu', 'jumlah_penduduk_jorong' => 467],
            ['id' => 689, 'nagari_id' => 17, 'nama_jorong' => 'Pasar Tanjung Ampalu', 'jumlah_penduduk_jorong' => 938],
            ['id' => 690, 'nagari_id' => 17, 'nama_jorong' => 'Mangkudu Kodok', 'jumlah_penduduk_jorong' => 1066],
            ['id' => 691, 'nagari_id' => 17, 'nama_jorong' => 'Taratak Malintang', 'jumlah_penduduk_jorong' => 1158],
            ['id' => 692, 'nagari_id' => 17, 'nama_jorong' => 'Sawah Gadang', 'jumlah_penduduk_jorong' => 365],
            ['id' => 693, 'nagari_id' => 17, 'nama_jorong' => 'Koto Panjang', 'jumlah_penduduk_jorong' => 1791],
            ['id' => 694, 'nagari_id' => 17, 'nama_jorong' => 'Batu Gandang', 'jumlah_penduduk_jorong' => 1532],
            ['id' => 695, 'nagari_id' => 17, 'nama_jorong' => 'Batu Balang', 'jumlah_penduduk_jorong' => 1613],
            ['id' => 696, 'nagari_id' => 17, 'nama_jorong' => 'Solok Badak', 'jumlah_penduduk_jorong' => 499],
            ['id' => 697, 'nagari_id' => 18, 'nama_jorong' => 'Koto Palaluar', 'jumlah_penduduk_jorong' => 517],
            ['id' => 698, 'nagari_id' => 18, 'nama_jorong' => 'Bungo', 'jumlah_penduduk_jorong' => 793],
            ['id' => 699, 'nagari_id' => 18, 'nama_jorong' => 'Ranah', 'jumlah_penduduk_jorong' => 951],
            ['id' => 700, 'nagari_id' => 18, 'nama_jorong' => 'Kampung Baru', 'jumlah_penduduk_jorong' => 436],
            ['id' => 701, 'nagari_id' => 18, 'nama_jorong' => 'Sumpadang', 'jumlah_penduduk_jorong' => 473],
            ['id' => 702, 'nagari_id' => 19, 'nama_jorong' => 'Buluh Rotan', 'jumlah_penduduk_jorong' => 890],
            ['id' => 703, 'nagari_id' => 19, 'nama_jorong' => 'Padang Lalang', 'jumlah_penduduk_jorong' => 357],
            ['id' => 704, 'nagari_id' => 19, 'nama_jorong' => 'Koto Guguk', 'jumlah_penduduk_jorong' => 1067],
            ['id' => 705, 'nagari_id' => 20, 'nama_jorong' => 'Teratak Betung', 'jumlah_penduduk_jorong' => null],
            ['id' => 706, 'nagari_id' => 20, 'nama_jorong' => 'Koto Padang Laweh', 'jumlah_penduduk_jorong' => null],
            ['id' => 707, 'nagari_id' => 20, 'nama_jorong' => 'Sungai Gemiri', 'jumlah_penduduk_jorong' => null],
            ['id' => 708, 'nagari_id' => 20, 'nama_jorong' => 'Bukik Gombak', 'jumlah_penduduk_jorong' => null],
            ['id' => 709, 'nagari_id' => 21, 'nama_jorong' => 'Kampung Juar', 'jumlah_penduduk_jorong' => 1389],
            ['id' => 710, 'nagari_id' => 21, 'nama_jorong' => 'Lumbaru', 'jumlah_penduduk_jorong' => 435],
            ['id' => 711, 'nagari_id' => 21, 'nama_jorong' => 'Koto Tanjung', 'jumlah_penduduk_jorong' => 1174],
            ['id' => 712, 'nagari_id' => 21, 'nama_jorong' => 'Ujung Padang', 'jumlah_penduduk_jorong' => 665],
            ['id' => 713, 'nagari_id' => 21, 'nama_jorong' => 'Tanjung Beringin', 'jumlah_penduduk_jorong' => 693],
            ['id' => 714, 'nagari_id' => 21, 'nama_jorong' => 'Taruko', 'jumlah_penduduk_jorong' => 473],
            ['id' => 715, 'nagari_id' => 21, 'nama_jorong' => 'Koto Tuo Tanjung', 'jumlah_penduduk_jorong' => 1477],
            ['id' => 716, 'nagari_id' => 22, 'nama_jorong' => 'Koto Mudik', 'jumlah_penduduk_jorong' => 547],
            ['id' => 717, 'nagari_id' => 22, 'nama_jorong' => 'Jalan Baru', 'jumlah_penduduk_jorong' => 332],
            ['id' => 718, 'nagari_id' => 22, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 517],
            ['id' => 719, 'nagari_id' => 22, 'nama_jorong' => 'Koto Hilir', 'jumlah_penduduk_jorong' => 669],
            ['id' => 720, 'nagari_id' => 23, 'nama_jorong' => 'Ranah Sigading', 'jumlah_penduduk_jorong' => 1651],
            ['id' => 721, 'nagari_id' => 23, 'nama_jorong' => 'Sungai Gemuruh', 'jumlah_penduduk_jorong' => 1069],
            ['id' => 722, 'nagari_id' => 23, 'nama_jorong' => 'Taratak Baru', 'jumlah_penduduk_jorong' => 1593],
            ['id' => 723, 'nagari_id' => 23, 'nama_jorong' => 'Sawah Tarok', 'jumlah_penduduk_jorong' => 585],
            ['id' => 724, 'nagari_id' => 23, 'nama_jorong' => 'Pasar Gambok', 'jumlah_penduduk_jorong' => 814],
            ['id' => 725, 'nagari_id' => 24, 'nama_jorong' => 'Batu Manjulur Barat', 'jumlah_penduduk_jorong' => 1094],
            ['id' => 726, 'nagari_id' => 24, 'nama_jorong' => 'Batu Manjulur Timur', 'jumlah_penduduk_jorong' => 789],
            ['id' => 727, 'nagari_id' => 25, 'nama_jorong' => 'Pamuatan Timur', 'jumlah_penduduk_jorong' => 887],
            ['id' => 728, 'nagari_id' => 25, 'nama_jorong' => 'Pamuatan Barat', 'jumlah_penduduk_jorong' => 767],
            ['id' => 729, 'nagari_id' => 26, 'nama_jorong' => 'Tapi Balai', 'jumlah_penduduk_jorong' => 1982],
            ['id' => 730, 'nagari_id' => 26, 'nama_jorong' => 'Kapalo Koto', 'jumlah_penduduk_jorong' => 1766],
            ['id' => 731, 'nagari_id' => 26, 'nama_jorong' => 'Guguk Tinggi', 'jumlah_penduduk_jorong' => 1365],
            ['id' => 732, 'nagari_id' => 26, 'nama_jorong' => 'Simancung', 'jumlah_penduduk_jorong' => 1335],
            ['id' => 733, 'nagari_id' => 26, 'nama_jorong' => 'Ladang Kapeh', 'jumlah_penduduk_jorong' => 1303],
            ['id' => 734, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Tongah', 'jumlah_penduduk_jorong' => 251],
            ['id' => 735, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Panjang', 'jumlah_penduduk_jorong' => 353],
            ['id' => 736, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Lamo', 'jumlah_penduduk_jorong' => 415],
            ['id' => 737, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Ateh', 'jumlah_penduduk_jorong' => 493],
            ['id' => 738, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Guguk Bulek', 'jumlah_penduduk_jorong' => 138],
            ['id' => 739, 'nagari_id' => 28, 'nama_jorong' => 'Andopan', 'jumlah_penduduk_jorong' => 681],
            ['id' => 740, 'nagari_id' => 28, 'nama_jorong' => 'Jambu Lipo', 'jumlah_penduduk_jorong' => 1613],
            ['id' => 741, 'nagari_id' => 28, 'nama_jorong' => 'Koto Tuo', 'jumlah_penduduk_jorong' => 2209],
            ['id' => 742, 'nagari_id' => 28, 'nama_jorong' => 'Padang Basiku', 'jumlah_penduduk_jorong' => 667],
            ['id' => 743, 'nagari_id' => 28, 'nama_jorong' => 'Silalak Kulik', 'jumlah_penduduk_jorong' => 699],
            ['id' => 744, 'nagari_id' => 28, 'nama_jorong' => 'Sungai Jodi', 'jumlah_penduduk_jorong' => 1018],
            ['id' => 745, 'nagari_id' => 28, 'nama_jorong' => 'Tigo Korong', 'jumlah_penduduk_jorong' => 745],
            ['id' => 746, 'nagari_id' => 29, 'nama_jorong' => 'Rumbai', 'jumlah_penduduk_jorong' => 561],
            ['id' => 747, 'nagari_id' => 29, 'nama_jorong' => 'Lalan', 'jumlah_penduduk_jorong' => 817],
            ['id' => 748, 'nagari_id' => 29, 'nama_jorong' => 'Batu Ajung', 'jumlah_penduduk_jorong' => 870],
            ['id' => 749, 'nagari_id' => 29, 'nama_jorong' => 'Batang Lalan', 'jumlah_penduduk_jorong' => 524],
            ['id' => 750, 'nagari_id' => 29, 'nama_jorong' => 'Sikaladi', 'jumlah_penduduk_jorong' => 762],
            ['id' => 751, 'nagari_id' => 30, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 1078],
            ['id' => 752, 'nagari_id' => 30, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 731],
            ['id' => 753, 'nagari_id' => 30, 'nama_jorong' => 'Taratak', 'jumlah_penduduk_jorong' => 966],
            ['id' => 754, 'nagari_id' => 31, 'nama_jorong' => 'Koto Kampung Dalam', 'jumlah_penduduk_jorong' => 524],
            ['id' => 755, 'nagari_id' => 31, 'nama_jorong' => 'Limau Sundai', 'jumlah_penduduk_jorong' => 830],
            ['id' => 756, 'nagari_id' => 31, 'nama_jorong' => 'Palintangan', 'jumlah_penduduk_jorong' => 576],
            ['id' => 757, 'nagari_id' => 32, 'nama_jorong' => 'Imbang Joyo', 'jumlah_penduduk_jorong' => 604],
            ['id' => 758, 'nagari_id' => 32, 'nama_jorong' => 'Taratak', 'jumlah_penduduk_jorong' => 354],
            ['id' => 759, 'nagari_id' => 32, 'nama_jorong' => 'Tanjung Korong', 'jumlah_penduduk_jorong' => 348],
            ['id' => 760, 'nagari_id' => 33, 'nama_jorong' => 'Ranah Lawe', 'jumlah_penduduk_jorong' => 329],
            ['id' => 761, 'nagari_id' => 33, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => 421],
            ['id' => 762, 'nagari_id' => 33, 'nama_jorong' => 'Pakorongan', 'jumlah_penduduk_jorong' => 426],
            ['id' => 763, 'nagari_id' => 34, 'nama_jorong' => 'Subarang Ombak', 'jumlah_penduduk_jorong' => null],
            ['id' => 764, 'nagari_id' => 34, 'nama_jorong' => 'Ilie Guguk Dadok', 'jumlah_penduduk_jorong' => null],
            ['id' => 765, 'nagari_id' => 34, 'nama_jorong' => 'Tongah', 'jumlah_penduduk_jorong' => null],
            ['id' => 766, 'nagari_id' => 34, 'nama_jorong' => 'Muaro Gambok', 'jumlah_penduduk_jorong' => null],
            ['id' => 767, 'nagari_id' => 34, 'nama_jorong' => 'Ilie Pasa Jumak', 'jumlah_penduduk_jorong' => null],
            ['id' => 768, 'nagari_id' => 34, 'nama_jorong' => 'Subarang Sukam', 'jumlah_penduduk_jorong' => null],
            ['id' => 769, 'nagari_id' => 34, 'nama_jorong' => 'Pematang Sari Bulan', 'jumlah_penduduk_jorong' => null],
            ['id' => 770, 'nagari_id' => 34, 'nama_jorong' => 'Pematang Anjung', 'jumlah_penduduk_jorong' => null],
            ['id' => 771, 'nagari_id' => 34, 'nama_jorong' => 'Pulau Berambai', 'jumlah_penduduk_jorong' => null],
            ['id' => 772, 'nagari_id' => 34, 'nama_jorong' => 'Batang Salosah', 'jumlah_penduduk_jorong' => null],
            ['id' => 773, 'nagari_id' => 36, 'nama_jorong' => 'Ranah Tanjung Bungo', 'jumlah_penduduk_jorong' => null],
            ['id' => 774, 'nagari_id' => 36, 'nama_jorong' => 'Sungai Abu', 'jumlah_penduduk_jorong' => null],
            ['id' => 775, 'nagari_id' => 36, 'nama_jorong' => 'Samiak', 'jumlah_penduduk_jorong' => null],
            ['id' => 776, 'nagari_id' => 36, 'nama_jorong' => 'Tanjung Medan', 'jumlah_penduduk_jorong' => null],
            ['id' => 777, 'nagari_id' => 36, 'nama_jorong' => 'Sankiamo', 'jumlah_penduduk_jorong' => null],
            ['id' => 778, 'nagari_id' => 37, 'nama_jorong' => 'Kalumpang', 'jumlah_penduduk_jorong' => 380],
            ['id' => 779, 'nagari_id' => 37, 'nama_jorong' => 'Sitampung', 'jumlah_penduduk_jorong' => 497],
            ['id' => 780, 'nagari_id' => 37, 'nama_jorong' => 'Pondok Jago', 'jumlah_penduduk_jorong' => 678],
            ['id' => 781, 'nagari_id' => 37, 'nama_jorong' => 'Koman Kocik', 'jumlah_penduduk_jorong' => 469],
            ['id' => 782, 'nagari_id' => 37, 'nama_jorong' => 'Parak Gadang', 'jumlah_penduduk_jorong' => 834],
            ['id' => 783, 'nagari_id' => 37, 'nama_jorong' => 'Pale', 'jumlah_penduduk_jorong' => 1009],
            ['id' => 784, 'nagari_id' => 37, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 909],
            ['id' => 785, 'nagari_id' => 37, 'nama_jorong' => 'Koran', 'jumlah_penduduk_jorong' => 894],
            ['id' => 786, 'nagari_id' => 37, 'nama_jorong' => 'Kambuik Koman', 'jumlah_penduduk_jorong' => 505],
            ['id' => 787, 'nagari_id' => 37, 'nama_jorong' => 'Limau Sundai', 'jumlah_penduduk_jorong' => 524],
            ['id' => 788, 'nagari_id' => 37, 'nama_jorong' => 'Duri', 'jumlah_penduduk_jorong' => 447],
            ['id' => 789, 'nagari_id' => 38, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => null],
            ['id' => 790, 'nagari_id' => 38, 'nama_jorong' => 'Koto Mudik', 'jumlah_penduduk_jorong' => null],
            ['id' => 791, 'nagari_id' => 38, 'nama_jorong' => 'Bukik Tujuh', 'jumlah_penduduk_jorong' => null],
            ['id' => 792, 'nagari_id' => 38, 'nama_jorong' => 'Rimbo Ambacang', 'jumlah_penduduk_jorong' => null],
            ['id' => 793, 'nagari_id' => 38, 'nama_jorong' => 'Takuang', 'jumlah_penduduk_jorong' => null],
            ['id' => 794, 'nagari_id' => 39, 'nama_jorong' => 'Batu Ranjau', 'jumlah_penduduk_jorong' => null],
            ['id' => 795, 'nagari_id' => 39, 'nama_jorong' => 'Bukik Buar', 'jumlah_penduduk_jorong' => null],
            ['id' => 796, 'nagari_id' => 39, 'nama_jorong' => 'Kampung Tarandam', 'jumlah_penduduk_jorong' => null],
            ['id' => 797, 'nagari_id' => 40, 'nama_jorong' => 'Koto Mudik', 'jumlah_penduduk_jorong' => null],
            ['id' => 798, 'nagari_id' => 40, 'nama_jorong' => 'Koto Ilie', 'jumlah_penduduk_jorong' => null],
            ['id' => 799, 'nagari_id' => 40, 'nama_jorong' => 'Pinang', 'jumlah_penduduk_jorong' => null],
            ['id' => 800, 'nagari_id' => 40, 'nama_jorong' => 'Tanggalo', 'jumlah_penduduk_jorong' => null],
            ['id' => 801, 'nagari_id' => 40, 'nama_jorong' => 'Silukah', 'jumlah_penduduk_jorong' => null],
            ['id' => 802, 'nagari_id' => 41, 'nama_jorong' => 'Koto Benek', 'jumlah_penduduk_jorong' => 555],
            ['id' => 803, 'nagari_id' => 41, 'nama_jorong' => 'Silabau', 'jumlah_penduduk_jorong' => 593],
            ['id' => 804, 'nagari_id' => 41, 'nama_jorong' => 'Kapalo Koto', 'jumlah_penduduk_jorong' => 535],
            ['id' => 805, 'nagari_id' => 41, 'nama_jorong' => 'Tanggalo', 'jumlah_penduduk_jorong' => 878],
            ['id' => 806, 'nagari_id' => 41, 'nama_jorong' => 'Padang Doto', 'jumlah_penduduk_jorong' => 575],
            ['id' => 807, 'nagari_id' => 41, 'nama_jorong' => 'Kulampi', 'jumlah_penduduk_jorong' => 220],
            ['id' => 808, 'nagari_id' => 41, 'nama_jorong' => 'Sungai Duo', 'jumlah_penduduk_jorong' => 436],
            ['id' => 809, 'nagari_id' => 42, 'nama_jorong' => 'Padang Ranah', 'jumlah_penduduk_jorong' => 679],
            ['id' => 810, 'nagari_id' => 42, 'nama_jorong' => 'Tapian Nanto', 'jumlah_penduduk_jorong' => 896],
            ['id' => 811, 'nagari_id' => 42, 'nama_jorong' => 'Kandang Harimau', 'jumlah_penduduk_jorong' => 744],
            ['id' => 812, 'nagari_id' => 42, 'nama_jorong' => 'Tapian Diaro', 'jumlah_penduduk_jorong' => 530],
            ['id' => 813, 'nagari_id' => 42, 'nama_jorong' => 'Kampung Berlian', 'jumlah_penduduk_jorong' => 934],
            ['id' => 814, 'nagari_id' => 42, 'nama_jorong' => 'Pudak', 'jumlah_penduduk_jorong' => 794],
            ['id' => 815, 'nagari_id' => 42, 'nama_jorong' => 'Kampung Baru', 'jumlah_penduduk_jorong' => 976],
            ['id' => 816, 'nagari_id' => 42, 'nama_jorong' => 'Pasar Sijunjung', 'jumlah_penduduk_jorong' => 922],
            ['id' => 817, 'nagari_id' => 42, 'nama_jorong' => 'Tanah Bato', 'jumlah_penduduk_jorong' => 1232],
            ['id' => 818, 'nagari_id' => 42, 'nama_jorong' => 'Ganting', 'jumlah_penduduk_jorong' => 2485],
            ['id' => 819, 'nagari_id' => 44, 'nama_jorong' => 'Simawik', 'jumlah_penduduk_jorong' => 552],
            ['id' => 820, 'nagari_id' => 44, 'nama_jorong' => 'Rumbai', 'jumlah_penduduk_jorong' => 466],
            ['id' => 821, 'nagari_id' => 44, 'nama_jorong' => 'Sungai Tampang', 'jumlah_penduduk_jorong' => 662],
            ['id' => 822, 'nagari_id' => 44, 'nama_jorong' => 'Sibolin', 'jumlah_penduduk_jorong' => 242],
            ['id' => 823, 'nagari_id' => 44, 'nama_jorong' => 'Koto Sisawah', 'jumlah_penduduk_jorong' => 485],
            ['id' => 824, 'nagari_id' => 44, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 536],
            ['id' => 825, 'nagari_id' => 44, 'nama_jorong' => 'Kabun', 'jumlah_penduduk_jorong' => 589],
            ['id' => 826, 'nagari_id' => 45, 'nama_jorong' => 'Koto Unggan', 'jumlah_penduduk_jorong' => 948],
            ['id' => 827, 'nagari_id' => 45, 'nama_jorong' => 'Unggan Bukik', 'jumlah_penduduk_jorong' => 783],
            ['id' => 828, 'nagari_id' => 45, 'nama_jorong' => 'Taratak Aro', 'jumlah_penduduk_jorong' => 604],
            ['id' => 829, 'nagari_id' => 45, 'nama_jorong' => 'Lubuak Batapuak Unggan', 'jumlah_penduduk_jorong' => 681],
            ['id' => 830, 'nagari_id' => 45, 'nama_jorong' => 'Kinkin', 'jumlah_penduduk_jorong' => 350],
            ['id' => 831, 'nagari_id' => 45, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 413],
            ['id' => 832, 'nagari_id' => 45, 'nama_jorong' => 'Koto Ateh', 'jumlah_penduduk_jorong' => 398],
            ['id' => 833, 'nagari_id' => 45, 'nama_jorong' => 'Ujung Koto', 'jumlah_penduduk_jorong' => 504],
            ['id' => 834, 'nagari_id' => 45, 'nama_jorong' => 'Batang Kinkin', 'jumlah_penduduk_jorong' => 426],
            ['id' => 835, 'nagari_id' => 46, 'nama_jorong' => 'Bonai', 'jumlah_penduduk_jorong' => 470],
            ['id' => 836, 'nagari_id' => 46, 'nama_jorong' => 'Koto Tinggi', 'jumlah_penduduk_jorong' => 465],
            ['id' => 837, 'nagari_id' => 46, 'nama_jorong' => 'Pauh', 'jumlah_penduduk_jorong' => 383],
            ['id' => 838, 'nagari_id' => 46, 'nama_jorong' => 'Loban Bungkuok', 'jumlah_penduduk_jorong' => 431],
            ['id' => 839, 'nagari_id' => 46, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 674],
            ['id' => 840, 'nagari_id' => 46, 'nama_jorong' => 'Koto Tangah', 'jumlah_penduduk_jorong' => 501],
            ['id' => 841, 'nagari_id' => 47, 'nama_jorong' => 'Pintu Rayo', 'jumlah_penduduk_jorong' => 388],
            ['id' => 842, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Ujung Luhak', 'jumlah_penduduk_jorong' => 420],
            ['id' => 843, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Tangah', 'jumlah_penduduk_jorong' => 328],
            ['id' => 844, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Sipuah', 'jumlah_penduduk_jorong' => 257],
            ['id' => 845, 'nagari_id' => 47, 'nama_jorong' => 'Tombang', 'jumlah_penduduk_jorong' => 470],
            ['id' => 846, 'nagari_id' => 47, 'nama_jorong' => 'Kampung Rajo', 'jumlah_penduduk_jorong' => 320],
            ['id' => 847, 'nagari_id' => 47, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 393],
            ['id' => 848, 'nagari_id' => 47, 'nama_jorong' => 'Batang Somi', 'jumlah_penduduk_jorong' => 440],
            ['id' => 849, 'nagari_id' => 47, 'nama_jorong' => 'Payo Sahadat', 'jumlah_penduduk_jorong' => 327],
            ['id' => 850, 'nagari_id' => 48, 'nama_jorong' => 'Sitongek', 'jumlah_penduduk_jorong' => 399],
            ['id' => 851, 'nagari_id' => 48, 'nama_jorong' => 'Koto Lamo', 'jumlah_penduduk_jorong' => 348],
            ['id' => 852, 'nagari_id' => 48, 'nama_jorong' => 'Pangkahan Sungai Laban', 'jumlah_penduduk_jorong' => 132],
            ['id' => 853, 'nagari_id' => 48, 'nama_jorong' => 'Simaru', 'jumlah_penduduk_jorong' => 520],
            ['id' => 854, 'nagari_id' => 48, 'nama_jorong' => 'Sitongek Selatan', 'jumlah_penduduk_jorong' => 277],
            ['id' => 855, 'nagari_id' => 48, 'nama_jorong' => 'Koto Lamo Utara', 'jumlah_penduduk_jorong' => 355],
            ['id' => 856, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Alam', 'jumlah_penduduk_jorong' => 801],
            ['id' => 857, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Raya', 'jumlah_penduduk_jorong' => 338],
            ['id' => 858, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Gadang', 'jumlah_penduduk_jorong' => 354],
            ['id' => 859, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Gadang Utara', 'jumlah_penduduk_jorong' => 362],
            ['id' => 860, 'nagari_id' => 50, 'nama_jorong' => 'Tapi Balai', 'jumlah_penduduk_jorong' => 466],
            ['id' => 861, 'nagari_id' => 50, 'nama_jorong' => 'Balai Lamo', 'jumlah_penduduk_jorong' => 578],
            ['id' => 862, 'nagari_id' => 50, 'nama_jorong' => 'Taruko', 'jumlah_penduduk_jorong' => 488],
            ['id' => 863, 'nagari_id' => 52, 'nama_jorong' => 'Simpang Tigo Sabiluru', 'jumlah_penduduk_jorong' => 560],
            ['id' => 864, 'nagari_id' => 52, 'nama_jorong' => 'Sipuah', 'jumlah_penduduk_jorong' => 419],
            ['id' => 865, 'nagari_id' => 52, 'nama_jorong' => 'Simpang Sawah Silupak', 'jumlah_penduduk_jorong' => 261],
            ['id' => 866, 'nagari_id' => 53, 'nama_jorong' => 'Pincuran Tujuh', 'jumlah_penduduk_jorong' => 666],
            ['id' => 867, 'nagari_id' => 53, 'nama_jorong' => 'Air Seriau', 'jumlah_penduduk_jorong' => 519],
            ['id' => 868, 'nagari_id' => 53, 'nama_jorong' => 'Payo Lawe', 'jumlah_penduduk_jorong' => 415],
            ['id' => 869, 'nagari_id' => 53, 'nama_jorong' => 'Kuok', 'jumlah_penduduk_jorong' => 396],
            ['id' => 870, 'nagari_id' => 53, 'nama_jorong' => 'Koto Puntian', 'jumlah_penduduk_jorong' => 300],
            ['id' => 871, 'nagari_id' => 53, 'nama_jorong' => 'Uncang Labuah', 'jumlah_penduduk_jorong' => 426],
            ['id' => 872, 'nagari_id' => 53, 'nama_jorong' => 'Calau', 'jumlah_penduduk_jorong' => 766],
            ['id' => 873, 'nagari_id' => 53, 'nama_jorong' => 'Kampung Baru', 'jumlah_penduduk_jorong' => 519],
            ['id' => 874, 'nagari_id' => 54, 'nama_jorong' => 'Balai-Balai', 'jumlah_penduduk_jorong' => 748],
            ['id' => 875, 'nagari_id' => 54, 'nama_jorong' => 'Koto Timbulun', 'jumlah_penduduk_jorong' => 867],
            ['id' => 876, 'nagari_id' => 54, 'nama_jorong' => 'Sibisir', 'jumlah_penduduk_jorong' => 957],
            ['id' => 877, 'nagari_id' => 54, 'nama_jorong' => 'Tandikek', 'jumlah_penduduk_jorong' => 629],
            ['id' => 878, 'nagari_id' => 55, 'nama_jorong' => 'Pasar Tanjung Gadang', 'jumlah_penduduk_jorong' => 456],
            ['id' => 879, 'nagari_id' => 55, 'nama_jorong' => 'Mudik Malih', 'jumlah_penduduk_jorong' => 137],
            ['id' => 880, 'nagari_id' => 55, 'nama_jorong' => 'Guguk Naneh', 'jumlah_penduduk_jorong' => 371],
            ['id' => 881, 'nagari_id' => 55, 'nama_jorong' => 'Pandam', 'jumlah_penduduk_jorong' => 193],
            ['id' => 882, 'nagari_id' => 55, 'nama_jorong' => 'Koto Baru', 'jumlah_penduduk_jorong' => 256],
            ['id' => 883, 'nagari_id' => 55, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => 306],
            ['id' => 884, 'nagari_id' => 55, 'nama_jorong' => 'Sungai Napar', 'jumlah_penduduk_jorong' => 136],
            ['id' => 885, 'nagari_id' => 55, 'nama_jorong' => 'Timbulun Patah', 'jumlah_penduduk_jorong' => 185],
            ['id' => 886, 'nagari_id' => 55, 'nama_jorong' => 'Kayu Gadih', 'jumlah_penduduk_jorong' => 227],
            ['id' => 887, 'nagari_id' => 56, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 166],
            ['id' => 888, 'nagari_id' => 56, 'nama_jorong' => 'Ranah Palam', 'jumlah_penduduk_jorong' => 144],
            ['id' => 889, 'nagari_id' => 56, 'nama_jorong' => 'Koto Ranah', 'jumlah_penduduk_jorong' => 109],
            ['id' => 890, 'nagari_id' => 57, 'nama_jorong' => 'Padang Laweh', 'jumlah_penduduk_jorong' => 538],
            ['id' => 891, 'nagari_id' => 57, 'nama_jorong' => 'Sungai Kandi', 'jumlah_penduduk_jorong' => 143],
            ['id' => 892, 'nagari_id' => 57, 'nama_jorong' => 'Koto Pulasan', 'jumlah_penduduk_jorong' => 720],
            ['id' => 893, 'nagari_id' => 57, 'nama_jorong' => 'Sawah Gadang', 'jumlah_penduduk_jorong' => 178],
            ['id' => 894, 'nagari_id' => 57, 'nama_jorong' => 'Ambacang', 'jumlah_penduduk_jorong' => 756],
            ['id' => 895, 'nagari_id' => 57, 'nama_jorong' => 'Pasar Pulasan', 'jumlah_penduduk_jorong' => 823],
            ['id' => 896, 'nagari_id' => 57, 'nama_jorong' => 'Batang Kati', 'jumlah_penduduk_jorong' => 484],
            ['id' => 897, 'nagari_id' => 58, 'nama_jorong' => 'Koto Langki', 'jumlah_penduduk_jorong' => 141],
            ['id' => 898, 'nagari_id' => 58, 'nama_jorong' => 'Liambang', 'jumlah_penduduk_jorong' => 271],
            ['id' => 899, 'nagari_id' => 58, 'nama_jorong' => 'Muaro Kaluai', 'jumlah_penduduk_jorong' => 82],
            ['id' => 900, 'nagari_id' => 58, 'nama_jorong' => 'Muaro Linggo', 'jumlah_penduduk_jorong' => 192],
            ['id' => 901, 'nagari_id' => 59, 'nama_jorong' => 'Bancah', 'jumlah_penduduk_jorong' => 173],
            ['id' => 902, 'nagari_id' => 59, 'nama_jorong' => 'Lubuk Tolang', 'jumlah_penduduk_jorong' => 87],
            ['id' => 903, 'nagari_id' => 59, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 270],
            ['id' => 904, 'nagari_id' => 60, 'nama_jorong' => 'Pasar Lamo', 'jumlah_penduduk_jorong' => 212],
            ['id' => 905, 'nagari_id' => 60, 'nama_jorong' => 'Bukik Sabalah', 'jumlah_penduduk_jorong' => 291],
            ['id' => 906, 'nagari_id' => 60, 'nama_jorong' => 'Koto', 'jumlah_penduduk_jorong' => 174],
            ['id' => 907, 'nagari_id' => 60, 'nama_jorong' => 'Batang Dikek', 'jumlah_penduduk_jorong' => 266],
            ['id' => 908, 'nagari_id' => 60, 'nama_jorong' => 'Pasar Baru', 'jumlah_penduduk_jorong' => 207],
            ['id' => 909, 'nagari_id' => 60, 'nama_jorong' => 'Tanjung Medan', 'jumlah_penduduk_jorong' => 219],
            ['id' => 910, 'nagari_id' => 61, 'nama_jorong' => 'Lubuk Cupak', 'jumlah_penduduk_jorong' => 232],
            ['id' => 911, 'nagari_id' => 61, 'nama_jorong' => 'Pisang Kolek', 'jumlah_penduduk_jorong' => 201],
            ['id' => 912, 'nagari_id' => 62, 'nama_jorong' => 'Koto Sinyamu', 'jumlah_penduduk_jorong' => 108],
            ['id' => 913, 'nagari_id' => 62, 'nama_jorong' => 'Polak Sinyamu', 'jumlah_penduduk_jorong' => 89],
            ['id' => 914, 'nagari_id' => 62, 'nama_jorong' => 'Kumbayak', 'jumlah_penduduk_jorong' => 95],
        ];

        foreach ($jorongs as $jorong) {
            Jorong::create($jorong);
        }
    }
}
