<?php

namespace Database\Seeders;

use App\Models\Jorong;
use Illuminate\Database\Seeder;

class JorongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jorongs = [
            ['id' => 1, 'nagari_id' => 1, 'nama_jorong' => 'Pantai Cermin'],
            ['id' => 2, 'nagari_id' => 1, 'nama_jorong' => 'Tambang Ameh'],
            ['id' => 3, 'nagari_id' => 1, 'nama_jorong' => 'Tanjung Udani'],
            ['id' => 4, 'nagari_id' => 1, 'nama_jorong' => 'Ranah Tibarau'],
            ['id' => 5, 'nagari_id' => 1, 'nama_jorong' => 'Lintas Harapan'],
            ['id' => 6, 'nagari_id' => 2, 'nama_jorong' => 'Pasar'],
            ['id' => 7, 'nagari_id' => 2, 'nama_jorong' => 'Simpang Ampek'],
            ['id' => 8, 'nagari_id' => 2, 'nama_jorong' => 'Koto Panjang'],
            ['id' => 9, 'nagari_id' => 3, 'nama_jorong' => 'Tanjung Pauh'],
            ['id' => 10, 'nagari_id' => 3, 'nama_jorong' => 'Dusun Tuo'],
            ['id' => 11, 'nagari_id' => 3, 'nama_jorong' => 'Bungo Pinang'],
            ['id' => 12, 'nagari_id' => 4, 'nama_jorong' => 'Ranah Pasar'],
            ['id' => 13, 'nagari_id' => 4, 'nama_jorong' => 'Kampung Pinang'],
            ['id' => 14, 'nagari_id' => 4, 'nama_jorong' => 'Tanjung Raya'],
            ['id' => 15, 'nagari_id' => 5, 'nama_jorong' => 'Bukik Malintang'],
            ['id' => 16, 'nagari_id' => 5, 'nama_jorong' => 'Rantau Jambu'],
            ['id' => 17, 'nagari_id' => 5, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 18, 'nagari_id' => 6, 'nama_jorong' => 'Cilacap'],
            ['id' => 19, 'nagari_id' => 6, 'nama_jorong' => 'Talang'],
            ['id' => 20, 'nagari_id' => 6, 'nama_jorong' => 'Koto'],
            ['id' => 21, 'nagari_id' => 6, 'nama_jorong' => 'Sikayan'],
            ['id' => 22, 'nagari_id' => 6, 'nama_jorong' => 'Sungai Ampang'],
            ['id' => 23, 'nagari_id' => 6, 'nama_jorong' => 'Pasar'],
            ['id' => 24, 'nagari_id' => 6, 'nama_jorong' => 'Batang Tonam'],
            ['id' => 25, 'nagari_id' => 7, 'nama_jorong' => 'Batang Kariang'],
            ['id' => 26, 'nagari_id' => 7, 'nama_jorong' => 'Galogah'],
            ['id' => 27, 'nagari_id' => 7, 'nama_jorong' => 'Kamang'],
            ['id' => 28, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Abadi'],
            ['id' => 29, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Bhakti'],
            ['id' => 30, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Makmur'],
            ['id' => 31, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Sejahtera'],
            ['id' => 32, 'nagari_id' => 7, 'nama_jorong' => 'Kurnia Kamang'],
            ['id' => 33, 'nagari_id' => 7, 'nama_jorong' => 'Simpang Kamang'],
            ['id' => 34, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Sentosa'],
            ['id' => 35, 'nagari_id' => 7, 'nama_jorong' => 'Kamang Madani'],
            ['id' => 36, 'nagari_id' => 8, 'nama_jorong' => 'Dusun Tinggi I'],
            ['id' => 37, 'nagari_id' => 8, 'nama_jorong' => 'Kiliran Jao'],
            ['id' => 38, 'nagari_id' => 8, 'nama_jorong' => 'Batu Talang'],
            ['id' => 39, 'nagari_id' => 8, 'nama_jorong' => 'Koto Lamo'],
            ['id' => 40, 'nagari_id' => 8, 'nama_jorong' => 'Batang Tiau'],
            ['id' => 41, 'nagari_id' => 8, 'nama_jorong' => 'Koto Rona'],
            ['id' => 42, 'nagari_id' => 8, 'nama_jorong' => 'Sungai Sariek'],
            ['id' => 43, 'nagari_id' => 9, 'nama_jorong' => 'Guguk Tinggi'],
            ['id' => 44, 'nagari_id' => 9, 'nama_jorong' => 'Koto Baru'],
            ['id' => 45, 'nagari_id' => 9, 'nama_jorong' => 'Banjar Tengah'],
            ['id' => 46, 'nagari_id' => 9, 'nama_jorong' => 'Lubuk Kapiek'],
            ['id' => 47, 'nagari_id' => 9, 'nama_jorong' => 'Koto Ronah'],
            ['id' => 48, 'nagari_id' => 9, 'nama_jorong' => 'Koto Tuo'],
            ['id' => 49, 'nagari_id' => 10, 'nama_jorong' => 'Koto'],
            ['id' => 50, 'nagari_id' => 10, 'nama_jorong' => 'Pasar'],
            ['id' => 51, 'nagari_id' => 10, 'nama_jorong' => 'Banjar Pematang'],
            ['id' => 52, 'nagari_id' => 11, 'nama_jorong' => 'Kunangan'],
            ['id' => 53, 'nagari_id' => 11, 'nama_jorong' => 'Parik Rantang'],
            ['id' => 54, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang I'],
            ['id' => 55, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang II'],
            ['id' => 56, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang III'],
            ['id' => 57, 'nagari_id' => 11, 'nama_jorong' => 'Sungai Tambang IV'],
            ['id' => 58, 'nagari_id' => 11, 'nama_jorong' => 'Mekar Jaya Sungai Tenang'],
            ['id' => 59, 'nagari_id' => 11, 'nama_jorong' => 'Suka Maju Sungai Tenang'],
            ['id' => 60, 'nagari_id' => 11, 'nama_jorong' => 'Suko Rejo Sungai Tenang'],
            ['id' => 61, 'nagari_id' => 12, 'nama_jorong' => 'Mudiak Imuak'],
            ['id' => 62, 'nagari_id' => 12, 'nama_jorong' => 'Parik Malintang'],
            ['id' => 63, 'nagari_id' => 12, 'nama_jorong' => 'Pincuran Tujuah'],
            ['id' => 64, 'nagari_id' => 13, 'nama_jorong' => 'Binuang Aie Putiah'],
            ['id' => 65, 'nagari_id' => 13, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 66, 'nagari_id' => 13, 'nama_jorong' => 'Muaro Buan'],
            ['id' => 67, 'nagari_id' => 13, 'nama_jorong' => 'Pintu Batu'],
            ['id' => 68, 'nagari_id' => 14, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 69, 'nagari_id' => 14, 'nama_jorong' => 'Lambah Gunung'],
            ['id' => 70, 'nagari_id' => 14, 'nama_jorong' => 'Ranah Pinago'],
            ['id' => 71, 'nagari_id' => 15, 'nama_jorong' => 'Dusun Tinggi II'],
            ['id' => 72, 'nagari_id' => 15, 'nama_jorong' => 'Koto Baru'],
            ['id' => 73, 'nagari_id' => 15, 'nama_jorong' => 'Lubuk Tarantang'],
            ['id' => 74, 'nagari_id' => 16, 'nama_jorong' => 'Koto Ranah'],
            ['id' => 75, 'nagari_id' => 16, 'nama_jorong' => 'Pasar'],
            ['id' => 76, 'nagari_id' => 16, 'nama_jorong' => 'Sungai Alai'],
            ['id' => 77, 'nagari_id' => 16, 'nama_jorong' => 'Sungai Gamuruah'],
            ['id' => 78, 'nagari_id' => 16, 'nama_jorong' => 'Tanjung Balik'],
            ['id' => 79, 'nagari_id' => 17, 'nama_jorong' => 'Aur Gading'],
            ['id' => 80, 'nagari_id' => 17, 'nama_jorong' => 'Tanjung Ampalu'],
            ['id' => 81, 'nagari_id' => 17, 'nama_jorong' => 'Pasar Tanjung Ampalu'],
            ['id' => 82, 'nagari_id' => 17, 'nama_jorong' => 'Mangkudu Kodok'],
            ['id' => 83, 'nagari_id' => 17, 'nama_jorong' => 'Koto Panjang'],
            ['id' => 84, 'nagari_id' => 17, 'nama_jorong' => 'Batu Gandang'],
            ['id' => 85, 'nagari_id' => 17, 'nama_jorong' => 'Batu Balang'],
            ['id' => 86, 'nagari_id' => 17, 'nama_jorong' => 'Solok Badak'],
            ['id' => 87, 'nagari_id' => 18, 'nama_jorong' => 'Koto Palaluar'],
            ['id' => 88, 'nagari_id' => 18, 'nama_jorong' => 'Bungo'],
            ['id' => 89, 'nagari_id' => 18, 'nama_jorong' => 'Ranah'],
            ['id' => 90, 'nagari_id' => 18, 'nama_jorong' => 'Kampung Baru'],
            ['id' => 91, 'nagari_id' => 18, 'nama_jorong' => 'Sumpadang'],
            ['id' => 92, 'nagari_id' => 19, 'nama_jorong' => 'Buluh Rotan'],
            ['id' => 93, 'nagari_id' => 19, 'nama_jorong' => 'Padang Lalang'],
            ['id' => 94, 'nagari_id' => 19, 'nama_jorong' => 'Koto Guguk'],
            ['id' => 95, 'nagari_id' => 20, 'nama_jorong' => 'Teratak Betung'],
            ['id' => 96, 'nagari_id' => 20, 'nama_jorong' => 'Koto Padang Laweh'],
            ['id' => 97, 'nagari_id' => 20, 'nama_jorong' => 'Sungai Gemiri'],
            ['id' => 98, 'nagari_id' => 20, 'nama_jorong' => 'Bukik Gombak'],
            ['id' => 99, 'nagari_id' => 21, 'nama_jorong' => 'Kampung Juar'],
            ['id' => 100, 'nagari_id' => 21, 'nama_jorong' => 'Lumbaru'],
            ['id' => 101, 'nagari_id' => 21, 'nama_jorong' => 'Koto Tanjung'],
            ['id' => 102, 'nagari_id' => 21, 'nama_jorong' => 'Ujung Padang'],
            ['id' => 103, 'nagari_id' => 21, 'nama_jorong' => 'Tanjung Beringin'],
            ['id' => 104, 'nagari_id' => 21, 'nama_jorong' => 'Taruko'],
            ['id' => 105, 'nagari_id' => 21, 'nama_jorong' => 'Koto Tuo Tanjung'],
            ['id' => 106, 'nagari_id' => 22, 'nama_jorong' => 'Koto Mudik'],
            ['id' => 107, 'nagari_id' => 22, 'nama_jorong' => 'Jalan Baru'],
            ['id' => 108, 'nagari_id' => 22, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 109, 'nagari_id' => 22, 'nama_jorong' => 'Koto Hilir'],
            ['id' => 110, 'nagari_id' => 23, 'nama_jorong' => 'Ranah Sigading'],
            ['id' => 111, 'nagari_id' => 23, 'nama_jorong' => 'Sungai Gemuruh'],
            ['id' => 112, 'nagari_id' => 23, 'nama_jorong' => 'Taratak Baru'],
            ['id' => 113, 'nagari_id' => 23, 'nama_jorong' => 'Sawah Tarok'],
            ['id' => 114, 'nagari_id' => 23, 'nama_jorong' => 'Pasar Gambok'],
            ['id' => 115, 'nagari_id' => 24, 'nama_jorong' => 'Batu Manjulur Barat'],
            ['id' => 116, 'nagari_id' => 24, 'nama_jorong' => 'Batu Manjulur Timur'],
            ['id' => 117, 'nagari_id' => 25, 'nama_jorong' => 'Pamuatan Timur'],
            ['id' => 118, 'nagari_id' => 25, 'nama_jorong' => 'Pamuatan Barat'],
            ['id' => 119, 'nagari_id' => 26, 'nama_jorong' => 'Tapi Balai'],
            ['id' => 120, 'nagari_id' => 26, 'nama_jorong' => 'Kapalo Koto'],
            ['id' => 121, 'nagari_id' => 26, 'nama_jorong' => 'Guguk Tinggi'],
            ['id' => 122, 'nagari_id' => 26, 'nama_jorong' => 'Simancung'],
            ['id' => 123, 'nagari_id' => 26, 'nama_jorong' => 'Ladang Kapeh'],
            ['id' => 124, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Tongah'],
            ['id' => 125, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Panjang'],
            ['id' => 126, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Lamo'],
            ['id' => 127, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Koto Ateh'],
            ['id' => 128, 'nagari_id' => 27, 'nama_jorong' => 'Dusun Guguk Bulek'],
            ['id' => 129, 'nagari_id' => 28, 'nama_jorong' => 'Andopan'],
            ['id' => 130, 'nagari_id' => 28, 'nama_jorong' => 'Jambu Lipo'],
            ['id' => 131, 'nagari_id' => 28, 'nama_jorong' => 'Koto Tuo'],
            ['id' => 132, 'nagari_id' => 28, 'nama_jorong' => 'Padang Basiku'],
            ['id' => 133, 'nagari_id' => 28, 'nama_jorong' => 'Silalak Kulik'],
            ['id' => 134, 'nagari_id' => 28, 'nama_jorong' => 'Sungai Jodi'],
            ['id' => 135, 'nagari_id' => 28, 'nama_jorong' => 'Tigo Korong'],
            ['id' => 136, 'nagari_id' => 29, 'nama_jorong' => 'Rumbai'],
            ['id' => 137, 'nagari_id' => 29, 'nama_jorong' => 'Lalan'],
            ['id' => 138, 'nagari_id' => 29, 'nama_jorong' => 'Batu Ajung'],
            ['id' => 139, 'nagari_id' => 29, 'nama_jorong' => 'Batang Lalan'],
            ['id' => 140, 'nagari_id' => 29, 'nama_jorong' => 'Sikaladi'],
            ['id' => 141, 'nagari_id' => 30, 'nama_jorong' => 'Koto'],
            ['id' => 142, 'nagari_id' => 30, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 143, 'nagari_id' => 30, 'nama_jorong' => 'Taratak'],
            ['id' => 144, 'nagari_id' => 31, 'nama_jorong' => 'Koto Kampung Dalam'],
            ['id' => 145, 'nagari_id' => 31, 'nama_jorong' => 'Limau Sundai'],
            ['id' => 146, 'nagari_id' => 31, 'nama_jorong' => 'Palintangan'],
            ['id' => 147, 'nagari_id' => 32, 'nama_jorong' => 'Imbang Joyo'],
            ['id' => 148, 'nagari_id' => 32, 'nama_jorong' => 'Taratak'],
            ['id' => 149, 'nagari_id' => 32, 'nama_jorong' => 'Tanjung Korong'],
            ['id' => 150, 'nagari_id' => 33, 'nama_jorong' => 'Ranah Lawe'],
            ['id' => 151, 'nagari_id' => 33, 'nama_jorong' => 'Koto Ranah'],
            ['id' => 152, 'nagari_id' => 33, 'nama_jorong' => 'Pakorongan'],
            ['id' => 153, 'nagari_id' => 34, 'nama_jorong' => 'Subarang Ombak'],
            ['id' => 154, 'nagari_id' => 34, 'nama_jorong' => 'Ilie Guguk Dadok'],
            ['id' => 155, 'nagari_id' => 34, 'nama_jorong' => 'Tongah'],
            ['id' => 156, 'nagari_id' => 34, 'nama_jorong' => 'Muaro Gambok'],
            ['id' => 157, 'nagari_id' => 34, 'nama_jorong' => 'Ilie Pasa Jumak'],
            ['id' => 158, 'nagari_id' => 34, 'nama_jorong' => 'Subarang Sukam'],
            ['id' => 159, 'nagari_id' => 34, 'nama_jorong' => 'Pematang Sari Bulan'],
            ['id' => 160, 'nagari_id' => 34, 'nama_jorong' => 'Pematang Anjung'],
            ['id' => 161, 'nagari_id' => 34, 'nama_jorong' => 'Pulau Berambai'],
            ['id' => 162, 'nagari_id' => 34, 'nama_jorong' => 'Batang Salosah'],
            ['id' => 163, 'nagari_id' => 36, 'nama_jorong' => 'Ranah Tanjung Bungo'],
            ['id' => 164, 'nagari_id' => 36, 'nama_jorong' => 'Sungai Abu'],
            ['id' => 165, 'nagari_id' => 36, 'nama_jorong' => 'Samiak'],
            ['id' => 166, 'nagari_id' => 36, 'nama_jorong' => 'Tanjung Medan'],
            ['id' => 167, 'nagari_id' => 36, 'nama_jorong' => 'Sankiamo'],
            ['id' => 168, 'nagari_id' => 37, 'nama_jorong' => 'Kalumpang'],
            ['id' => 169, 'nagari_id' => 37, 'nama_jorong' => 'Sitampung'],
            ['id' => 170, 'nagari_id' => 37, 'nama_jorong' => 'Pondok Jago'],
            ['id' => 171, 'nagari_id' => 37, 'nama_jorong' => 'Koman Kocik'],
            ['id' => 172, 'nagari_id' => 37, 'nama_jorong' => 'Parak Gadang'],
            ['id' => 173, 'nagari_id' => 37, 'nama_jorong' => 'Pale'],
            ['id' => 174, 'nagari_id' => 37, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 175, 'nagari_id' => 37, 'nama_jorong' => 'Koran'],
            ['id' => 176, 'nagari_id' => 37, 'nama_jorong' => 'Kambuik Koman'],
            ['id' => 177, 'nagari_id' => 37, 'nama_jorong' => 'Limau Sundai'],
            ['id' => 178, 'nagari_id' => 37, 'nama_jorong' => 'Duri'],
            ['id' => 179, 'nagari_id' => 38, 'nama_jorong' => 'Koto Ranah'],
            ['id' => 180, 'nagari_id' => 38, 'nama_jorong' => 'Koto Mudik'],
            ['id' => 181, 'nagari_id' => 38, 'nama_jorong' => 'Bukik Tujuh'],
            ['id' => 182, 'nagari_id' => 38, 'nama_jorong' => 'Rimbo Ambacang'],
            ['id' => 183, 'nagari_id' => 38, 'nama_jorong' => 'Takuang'],
            ['id' => 184, 'nagari_id' => 39, 'nama_jorong' => 'Batu Ranjau'],
            ['id' => 185, 'nagari_id' => 39, 'nama_jorong' => 'Bukik Buar'],
            ['id' => 186, 'nagari_id' => 39, 'nama_jorong' => 'Kampung Tarandam'],
            ['id' => 187, 'nagari_id' => 40, 'nama_jorong' => 'Koto Mudik'],
            ['id' => 188, 'nagari_id' => 40, 'nama_jorong' => 'Koto Ilie'],
            ['id' => 189, 'nagari_id' => 40, 'nama_jorong' => 'Pinang'],
            ['id' => 190, 'nagari_id' => 40, 'nama_jorong' => 'Tanggalo'],
            ['id' => 191, 'nagari_id' => 40, 'nama_jorong' => 'Silukah'],
            ['id' => 192, 'nagari_id' => 41, 'nama_jorong' => 'Koto Benek'],
            ['id' => 193, 'nagari_id' => 41, 'nama_jorong' => 'Silabau'],
            ['id' => 194, 'nagari_id' => 41, 'nama_jorong' => 'Kapalo Koto'],
            ['id' => 195, 'nagari_id' => 41, 'nama_jorong' => 'Tanggalo'],
            ['id' => 196, 'nagari_id' => 41, 'nama_jorong' => 'Padang Doto'],
            ['id' => 197, 'nagari_id' => 41, 'nama_jorong' => 'Kulampi'],
            ['id' => 198, 'nagari_id' => 41, 'nama_jorong' => 'Sungai Duo'],
            ['id' => 199, 'nagari_id' => 42, 'nama_jorong' => 'Padang Ranah'],
            ['id' => 200, 'nagari_id' => 42, 'nama_jorong' => 'Tapian Nanto'],
            ['id' => 201, 'nagari_id' => 42, 'nama_jorong' => 'Kandang Harimau'],
            ['id' => 202, 'nagari_id' => 42, 'nama_jorong' => 'Tapian Diaro'],
            ['id' => 203, 'nagari_id' => 42, 'nama_jorong' => 'Kampung Berlian'],
            ['id' => 204, 'nagari_id' => 42, 'nama_jorong' => 'Pudak'],
            ['id' => 205, 'nagari_id' => 42, 'nama_jorong' => 'Kampung Baru'],
            ['id' => 206, 'nagari_id' => 42, 'nama_jorong' => 'Pasar Sijunjung'],
            ['id' => 207, 'nagari_id' => 42, 'nama_jorong' => 'Tanah Bato'],
            ['id' => 208, 'nagari_id' => 42, 'nama_jorong' => 'Ganting'],
            ['id' => 209, 'nagari_id' => 44, 'nama_jorong' => 'Simawik'],
            ['id' => 210, 'nagari_id' => 44, 'nama_jorong' => 'Rumbai'],
            ['id' => 211, 'nagari_id' => 44, 'nama_jorong' => 'Sungai Tampang'],
            ['id' => 212, 'nagari_id' => 44, 'nama_jorong' => 'Sibolin'],
            ['id' => 213, 'nagari_id' => 44, 'nama_jorong' => 'Koto Sisawah'],
            ['id' => 214, 'nagari_id' => 44, 'nama_jorong' => 'Koto Baru'],
            ['id' => 215, 'nagari_id' => 44, 'nama_jorong' => 'Kabun'],
            ['id' => 216, 'nagari_id' => 45, 'nama_jorong' => 'Koto Unggan'],
            ['id' => 217, 'nagari_id' => 45, 'nama_jorong' => 'Unggan Bukik'],
            ['id' => 218, 'nagari_id' => 45, 'nama_jorong' => 'Taratak Aro'],
            ['id' => 219, 'nagari_id' => 45, 'nama_jorong' => 'Lubuak Batapuak Unggan'],
            ['id' => 220, 'nagari_id' => 45, 'nama_jorong' => 'Kinkin'],
            ['id' => 221, 'nagari_id' => 45, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 222, 'nagari_id' => 45, 'nama_jorong' => 'Koto Ateh'],
            ['id' => 223, 'nagari_id' => 45, 'nama_jorong' => 'Ujung Koto'],
            ['id' => 224, 'nagari_id' => 45, 'nama_jorong' => 'Batang Kinkin'],
            ['id' => 225, 'nagari_id' => 46, 'nama_jorong' => 'Bonai'],
            ['id' => 226, 'nagari_id' => 46, 'nama_jorong' => 'Koto Tinggi'],
            ['id' => 227, 'nagari_id' => 46, 'nama_jorong' => 'Pauh'],
            ['id' => 228, 'nagari_id' => 46, 'nama_jorong' => 'Loban Bungkuok'],
            ['id' => 229, 'nagari_id' => 46, 'nama_jorong' => 'Koto Baru'],
            ['id' => 230, 'nagari_id' => 46, 'nama_jorong' => 'Koto Tangah'],
            ['id' => 231, 'nagari_id' => 47, 'nama_jorong' => 'Pintu Rayo'],
            ['id' => 232, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Ujung Luhak'],
            ['id' => 233, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Tangah'],
            ['id' => 234, 'nagari_id' => 47, 'nama_jorong' => 'Taratak Sipuah'],
            ['id' => 235, 'nagari_id' => 47, 'nama_jorong' => 'Tombang'],
            ['id' => 236, 'nagari_id' => 47, 'nama_jorong' => 'Kampung Rajo'],
            ['id' => 237, 'nagari_id' => 47, 'nama_jorong' => 'Koto'],
            ['id' => 238, 'nagari_id' => 47, 'nama_jorong' => 'Batang Somi'],
            ['id' => 239, 'nagari_id' => 47, 'nama_jorong' => 'Payo Sahadat'],
            ['id' => 240, 'nagari_id' => 48, 'nama_jorong' => 'Sitongek'],
            ['id' => 241, 'nagari_id' => 48, 'nama_jorong' => 'Koto Lamo'],
            ['id' => 242, 'nagari_id' => 48, 'nama_jorong' => 'Pangkahan Sungai Laban'],
            ['id' => 243, 'nagari_id' => 48, 'nama_jorong' => 'Simaru'],
            ['id' => 244, 'nagari_id' => 48, 'nama_jorong' => 'Sitongek Selatan'],
            ['id' => 245, 'nagari_id' => 48, 'nama_jorong' => 'Koto Lamo Utara'],
            ['id' => 246, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Alam'],
            ['id' => 247, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Raya'],
            ['id' => 248, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Gadang'],
            ['id' => 249, 'nagari_id' => 49, 'nama_jorong' => 'Tanjung Gadang Utara'],
            ['id' => 250, 'nagari_id' => 50, 'nama_jorong' => 'Tapi Balai'],
            ['id' => 251, 'nagari_id' => 50, 'nama_jorong' => 'Balai Lamo'],
            ['id' => 252, 'nagari_id' => 50, 'nama_jorong' => 'Taruko'],
            ['id' => 253, 'nagari_id' => 52, 'nama_jorong' => 'Simpang Tigo Sabiluru'],
            ['id' => 254, 'nagari_id' => 52, 'nama_jorong' => 'Sipuah'],
            ['id' => 255, 'nagari_id' => 52, 'nama_jorong' => 'Simpang Sawah Silupak'],
            ['id' => 256, 'nagari_id' => 53, 'nama_jorong' => 'Pincuran Tujuh'],
            ['id' => 257, 'nagari_id' => 53, 'nama_jorong' => 'Air Seriau'],
            ['id' => 258, 'nagari_id' => 53, 'nama_jorong' => 'Payo Lawe'],
            ['id' => 259, 'nagari_id' => 53, 'nama_jorong' => 'Kuok'],
            ['id' => 260, 'nagari_id' => 53, 'nama_jorong' => 'Koto Puntian'],
            ['id' => 261, 'nagari_id' => 53, 'nama_jorong' => 'Uncang Labuah'],
            ['id' => 262, 'nagari_id' => 53, 'nama_jorong' => 'Calau'],
            ['id' => 263, 'nagari_id' => 53, 'nama_jorong' => 'Kampung Baru'],
            ['id' => 264, 'nagari_id' => 54, 'nama_jorong' => 'Balai-Balai'],
            ['id' => 265, 'nagari_id' => 54, 'nama_jorong' => 'Koto Timbulun'],
            ['id' => 266, 'nagari_id' => 54, 'nama_jorong' => 'Sibisir'],
            ['id' => 267, 'nagari_id' => 54, 'nama_jorong' => 'Tandikek'],
            ['id' => 268, 'nagari_id' => 55, 'nama_jorong' => 'Pasar Tanjung Gadang'],
            ['id' => 269, 'nagari_id' => 55, 'nama_jorong' => 'Mudik Malih'],
            ['id' => 270, 'nagari_id' => 55, 'nama_jorong' => 'Guguk Naneh'],
            ['id' => 271, 'nagari_id' => 55, 'nama_jorong' => 'Pandam'],
            ['id' => 272, 'nagari_id' => 55, 'nama_jorong' => 'Koto Baru'],
            ['id' => 273, 'nagari_id' => 55, 'nama_jorong' => 'Koto Ranah'],
            ['id' => 274, 'nagari_id' => 55, 'nama_jorong' => 'Sungai Napar'],
            ['id' => 275, 'nagari_id' => 55, 'nama_jorong' => 'Timbulun Patah'],
            ['id' => 276, 'nagari_id' => 55, 'nama_jorong' => 'Kayu Gadih'],
            ['id' => 277, 'nagari_id' => 56, 'nama_jorong' => 'Koto'],
            ['id' => 278, 'nagari_id' => 56, 'nama_jorong' => 'Ranah Palam'],
            ['id' => 279, 'nagari_id' => 56, 'nama_jorong' => 'Koto Ranah'],
            ['id' => 280, 'nagari_id' => 57, 'nama_jorong' => 'Padang Laweh'],
            ['id' => 281, 'nagari_id' => 57, 'nama_jorong' => 'Sungai Kandi'],
            ['id' => 282, 'nagari_id' => 57, 'nama_jorong' => 'Koto Pulasan'],
            ['id' => 283, 'nagari_id' => 57, 'nama_jorong' => 'Sawah Gadang'],
            ['id' => 284, 'nagari_id' => 57, 'nama_jorong' => 'Ambacang'],
            ['id' => 285, 'nagari_id' => 57, 'nama_jorong' => 'Pasar Pulasan'],
            ['id' => 286, 'nagari_id' => 57, 'nama_jorong' => 'Batang Kati'],
            ['id' => 287, 'nagari_id' => 58, 'nama_jorong' => 'Koto Langki'],
            ['id' => 288, 'nagari_id' => 58, 'nama_jorong' => 'Liambang'],
            ['id' => 289, 'nagari_id' => 58, 'nama_jorong' => 'Muaro Kaluai'],
            ['id' => 290, 'nagari_id' => 58, 'nama_jorong' => 'Muaro Linggo'],
            ['id' => 291, 'nagari_id' => 59, 'nama_jorong' => 'Bancah'],
            ['id' => 292, 'nagari_id' => 59, 'nama_jorong' => 'Lubuk Tolang'],
            ['id' => 293, 'nagari_id' => 59, 'nama_jorong' => 'Koto'],
            ['id' => 294, 'nagari_id' => 60, 'nama_jorong' => 'Pasar Lamo'],
            ['id' => 295, 'nagari_id' => 60, 'nama_jorong' => 'Bukik Sabalah'],
            ['id' => 296, 'nagari_id' => 60, 'nama_jorong' => 'Koto'],
            ['id' => 297, 'nagari_id' => 60, 'nama_jorong' => 'Batang Dikek'],
            ['id' => 298, 'nagari_id' => 60, 'nama_jorong' => 'Pasar Baru'],
            ['id' => 299, 'nagari_id' => 60, 'nama_jorong' => 'Tanjung Medan'],
            ['id' => 300, 'nagari_id' => 61, 'nama_jorong' => 'Lubuk Cupak'],
            ['id' => 301, 'nagari_id' => 61, 'nama_jorong' => 'Pisang Kolek'],
            ['id' => 302, 'nagari_id' => 62, 'nama_jorong' => 'Koto Sinyamu'],
            ['id' => 303, 'nagari_id' => 62, 'nama_jorong' => 'Polak Sinyamu'],
            ['id' => 304, 'nagari_id' => 62, 'nama_jorong' => 'Kumbayak'],
        ];

        foreach ($jorongs as $jorong) {
            Jorong::create($jorong);
        }
    }
}
